version: '2'

services:
  mysql:
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    image: mysql:5.7
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=softdelete_traps
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
  web:
    restart: always
    privileged: true
    hostname: softdelete-traps
    image: sawadashota/centos73_php71_laravel:latest
    links:
      - mysql
    volumes:
      - .:/var/www/html/app
    ports:
      - 8080:80
    command: /sbin/init